### ISSUE TITLE
Count value not changing on storybook

### ISSUE THREAD

**Issue by saggypatel** [bmpickford/lit-element-typescript-storybook-starter#1]
Not sure if I'm missing anything, after clicking on button it doesn't increment the count. Below is the example, when I logged it, count value is being changed.  I'm running `build:watch` and `storybook`
Also, in this example I'm passing an arg value of 1, that's why its starting from 1

![Screen Shot 2021-07-15 at 12 17 25 PM](https://user-images.githubusercontent.com/9377490/125845407-69676cb2-9741-47d0-899b-c6aa52e8b116.png)

**Comment by bmpickford** [comment]
Thanks for raising. Seems to be related to https://github.com/storybookjs/storybook/issues/12578

Will investigate some of the fixes suggested and try to push up a fix soon
